services:
  postgres:
    image: postgres:16
    container_name: bridgeops_postgres
    restart: always
    environment:
      POSTGRES_DB: bridgeops_ai
      POSTGRES_USER: bridgeops_user
      POSTGRES_PASSWORD: bridgeops_password
    ports:
      - "5432:5432"
    volumes:
      - bridgeops_postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: bridgeops_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@bridgeops.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  bridgeops_postgres_data:
