---

- name: Install git

  dnf:

    name: git

    state: present

- name: Download Helm install script

  get_url:

    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3

    dest: /tmp/get-helm.sh

    owner: root

    group: root

    mode: '0700'

- name: Run Helm install script

  shell: /tmp/get-helm.sh

  args:

    creates: /usr/local/bin/helm

- name: Verify Helm installed

  command: /usr/local/bin/helm version

  register: helm_version

- debug:

    msg: "{{ helm_version.stdout }}"
