apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: laravel-ingress
  labels:
    app: bridgeops
    component: web
  annotations:
    # Menggunakan Nginx Ingress Controller
    kubernetes.io/ingress.class: nginx
    
    # Untuk otomatisasi SSL Certificate via cert-manager (Let's Encrypt)
    # cert-manager.io/cluster-issuer: letsencrypt-prod
    
    # Limit max upload size di Ingress
    nginx.ingress.kubernetes.io/proxy-body-size: "64m"
spec:
  rules:
    - host: bridgeops.local # Ganti dengan domain rill Anda (contoh: bridgeops.com)
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: laravel-service
                port:
                  number: 80
  # Uncomment block di bawah ini jika domain sudah terhubung dan cert-manager sudah siap
  # tls:
  #   - hosts:
  #       - bridgeops.local
  #     secretName: bridgeops-tls-cert
