name: Main Release Trigger

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  default-ci:
    name: Run Default CI
    uses: ./.github/workflows/ci-cd.yml

  application-gateway:
    name: Run Application Security Gateway
    needs: default-ci
    uses: ./.github/workflows/application-gateway.yml

  container-scan-push:
    name: Scan and Push Container Image
    needs: application-gateway
    uses: ./.github/workflows/docker-build-push.yml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
